# Site settings
title: 
email: huoen.wyk@taobao.com
description: > # this means to ignore newlines until "baseurl:"
   爱玩桌上足球,爱敲代码.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.weiyuke.net" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: goodpress 

# Build settings
#markdown: kramdown
markdown: redcarpet
